In [1]:
import pandas as pd

In [2]:
pd.options.display.max_columns=999

In [3]:
sample_submission_path = '../Data/sample_submission.csv'
train_path = '../Data/train.csv'

In [4]:
pd.read_csv(sample_submission_path).head(2)

   ID  PredictedProb
0   0            0.5
1   1            0.5

In [5]:
train = pd.read_csv(train_path)

In [6]:
train.shape

(114321, 133)

In [7]:
pd.DataFrame(pd.isnull(train).sum()).T

,ID,target,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13,v14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24,v25,v26,v27,v28,v29,v30,v31,v32,v33,v34,v35,v36,v37,v38,v39,v40,v41,v42,v43,v44,v45,v46,v47,v48,v49,v50,v51,v52,v53,v54,v55,v56,v57,v58,v59,v60,v61,v62,v63,v64,v65,v66,v67,v68,v69,v70,v71,v72,v73,v74,v75,v76,v77,v78,v79,v80,v81,v82,v83,v84,v85,v86,v87,v88,v89,v90,v91,v92,v93,v94,v95,v96,v97,v98,v99,v100,v101,v102,v103,v104,v105,v106,v107,v108,v109,v110,v111,v112,v113,v114,v115,v116,v117,v118,v119,v120,v121,v122,v123,v124,v125,v126,v127,v128,v129,v130,v131
0,0,0,49832,49796,3457,49796,48624,49832,49832,48619,49851,84,49836,86,49832,4,49836,49895,49796,49832,49843,49840,611,500,50675,0,48619,49832,49832,49832,49832,60110,3457,49832,49832,111,49832,48624,49843,0,49836,111,49832,49832,49836,49796,49832,48619,0,49796,49832,86,50678,3,49836,48619,49832,6882,49832,49836,49796,49832,49796,0,48619,49796,49840,0,49832,49836,49895,48636,0,0,49836,0,0,49796,49832,49895,0,49851,48624,48624,49832,49832,50682,49832,48663,49832,48619,49836,3,49843,49832,49832,49843,49832,49843,48654,49832,49836,49796,51316,49832,49832,48658,49796,3,48624,48624,0,49832,382,55304,30,49895,49836,48624,49843,50680,49836,49840,49851,50678,48619,77,49832,49832,48624,0,49843,49895

In [8]:
y=train.target

In [9]:
X = train.drop(labels=['target'], axis=1)

In [10]:
train.shape

(114321, 133)

In [11]:
X.shape

(114321, 132)

In [12]:
y.shape

(114321,)

In [13]:
columns_categorical = X.dtypes[X.dtypes=='object'].index

In [14]:
columns_categorical

Index(['v3', 'v22', 'v24', 'v30', 'v31', 'v47', 'v52', 'v56', 'v66', 'v71',
       'v74', 'v75', 'v79', 'v91', 'v107', 'v110', 'v112', 'v113', 'v125'],
      dtype='object')

In [15]:
X_categorical = X[columns_categorical]

In [16]:
dummy_dfs=[]
for i in range (X_categorical.shape[1]):
    dummy_dfs.append(pd.get_dummies(X_categorical.ix[:,i]))

In [17]:
len(dummy_dfs)

19

In [24]:
X_categorical['v24'].unique()

array(['C', 'E', 'D', 'A', 'B'], dtype=object)

In [23]:
X_categorical['v30'].unique()

array(['C', nan, 'G', 'D', 'B', 'F', 'A', 'E'], dtype=object)

In [18]:
pd.concat(dummy_dfs[2:4], axis=1)

        A  B  C  D  E  A  B  C  D  E  F  G
0       0  0  1  0  0  0  0  1  0  0  0  0
1       0  0  1  0  0  0  0  1  0  0  0  0
2       0  0  0  0  1  0  0  0  0  0  0  0
3       0  0  0  1  0  0  0  1  0  0  0  0
4       0  0  0  0  1  0  0  0  0  0  0  0
5       1  0  0  0  0  0  0  0  0  0  0  0
6       0  0  0  0  1  0  0  0  0  0  0  1
7       0  0  0  1  0  0  0  1  0  0  0  0
8       0  0  0  0  1  0  0  0  0  0  0  0
9       0  0  1  0  0  0  0  1  0  0  0  0
10      0  0  0  0  1  0  0  0  1  0  0  0
11      0  0  0  1  0  0  0  0  0  0  0  1
12      0  0  0  0  1  0  0  0  0  0  0  0
13      0  0  1  0  0  0  0  0  0  0  0  0
14      0  0  0  0  1  0  1  0  0  0  0  0
15      0  0  0  0  1  0  0  0  0  0  0  0
16      0  0  0  0  1  0  0  0  0  0  0  1
17      0  0  0  1  0  0  0  1  0  0  0  0
18      0  0  1  0  0  0  0  0  0  0  0  0
19      0  0  1  0  0  0  0  0  0  0  1  0
20      0  0  1  0  0  0  0  0  0  0  0  0
21      0  0  0  0  1  0  0  0  0  0  0  1
22      0  0  0  0  1  0  0  0  0  0  0  0
23      0  0  1  0  0  0  0  0  1  0  0  0
24      0  0  1  0  0  1  0  0  0  0  0  0
25      0  0  0  0  1  0  0  0  0  0  0  0
26      0  0  0  0  1  0  0  0  0  0  0  0
27      1  0  0  0  0  0  0  1  0  0  0  0
28      0  0  0  0  1  0  0  0  0  0  0  0
29      0  0  0  0  1  0  0  0  0  0  0  0
...    .. .. .. .. .. .. .. .. .. .. .. ..
114291  0  0  0  0  1  0  0  0  0  0  0  0
114292  0  0  0  1  0  0  0  0  0  0  0  0
114293  0  0  0  1  0  0  0  0  0  0  0  0
114294  0  0  0  0  1  0  0  0  0  0  0  0
114295  0  0  1  0  0  0  0  0  0  0  0  0
114296  0  1  0  0  0  0  0  0  0  0  0  0
114297  0  0  0  0  1  0  0  1  0  0  0  0
114298  0  0  1  0  0  0  0  1  0  0  0  0
114299  0  0  0  1  0  0  0  1  0  0  0  0
114300  0  0  0  1  0  0  0  1  0  0  0  0
114301  0  0  0  0  1  0  0  0  0  0  0  0
114302  0  0  0  0  1  0  0  0  0  0  0  0
114303  0  0  0  0  1  0  0  1  0  0  0  0
114304  0  0  0  1  0  0  0  0  0  0  0  0
114305  0  0  0  0  1  0  0  0  0  0  0  0
114306  0  0  1  0  0  0  0  1  0  0  0  0
114307  1  0  0  0  0  0  0  0  0  0  0  0
114308  0  0  0  0  1  0  0  0  0  0  0  0
114309  0  0  0  0  1  0  0  0  0  0  0  0
114310  0  0  0  0  1  0  0  0  0  0  0  0
114311  0  0  0  0  1  0  0  0  0  0  0  0
114312  0  0  0  1  0  0  0  1  0  0  0  0
114313  1  0  0  0  0  0  0  0  0  1  0  0
114314  0  0  1  0  0  0  0  1  0  0  0  0
114315  0  0  0  0  1  0  0  0  0  0  0  0
114316  0  0  0  0  1  0  0  0  0  0  0  0
114317  0  0  0  1  0  0  0  0  0  0  0  0
114318  1  0  0  0  0  0  0  1  0  0  0  0
114319  0  0  0  1  0  0  0  0  0  0  0  1
114320  0  0  1  0  0  0  0  1  0  0  0  0

[114321 rows x 12 columns]

In [29]:
for i in range (len(dummy_dfs)):
    print (dummy_dfs[i].shape)

(114321, 3)
(114321, 18210)
(114321, 5)
(114321, 7)
(114321, 3)
(114321, 10)
(114321, 12)
(114321, 122)
(114321, 3)
(114321, 9)
(114321, 3)
(114321, 4)
(114321, 18)
(114321, 7)
(114321, 7)
(114321, 3)
(114321, 22)
(114321, 36)
(114321, 90)

In [20]:
for i in range (0, len(dummy_dfs),2):
    pd.concat(dummy_dfs[i:i+1]).to_csv('../Data/dummy_df'+str(i)+str(i+1))
    print (i)

0
2
4
6
8
10
12
14
16
18

In [21]:
for i in range (0, len(dummy_dfs),4):
    df1 = pd.read_csv('../Data/dummy_df'+str(i)+str(i+1))
    df2 = pd.read_csv('../Data/dummy_df'+str(i+2)+str(i+3))
    pd.concat([df1,df2]).to_csv('../Data/dummy_df_new'+str(i)+str(i+3))
    print(i)

0
4
8
12
16

In [23]:
for i in range (0, len(dummy_dfs),8):
    df1 = pd.read_csv('../Data/dummy_df_new'+str(i)+str(i+3))
    df2 = pd.read_csv('../Data/dummy_df_new'+str(i+4)+str(i+7))
    pd.concat([df1,df2]).to_csv('../Data/dummy_df_new_bis_'+str(i)+str(i+7))
    print(i)

0
8

OSError: File b'../Data/dummy_df_new2023' does not exist

In [24]:
df1 = pd.concat ([pd.read_csv('../Data/dummy_df_new_bis_07'),pd.read_csv('../Data/dummy_df_new_bis_815')])

AssertionError: Number of manager items must equal union of block items
# manager items: 20, # tot_items: 21

In [25]:
df1 = pd.read_csv('../Data/dummy_df_new_bis_07')

In [26]:
df1.shape

(457284, 15)

In [27]:
X.shape

(114321, 132)

In [28]:
df1

,Unnamed: 0,A,B,C,D,E,F,G,H,I,J,K,L,Unnamed: 0.1,Unnamed: 0.1
0,0,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,1,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
2,2,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2
3,3,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3
4,4,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4
5,5,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5
6,6,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,6
7,7,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,7
8,8,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,8
9,9,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,9
10,10,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,10
11,11,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,11
12,12,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,12
13,13,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,13
14,14,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,14
15,15,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,15
16,16,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,16
17,17,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,17
18,18,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,18
19,19,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,19
20,20,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,20
21,21,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,21
22,22,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,22
23,23,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23,23
24,24,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,24
25,25,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25,25
26,26,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,26
27,27,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,27
28,28,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,28
29,29,0,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457254,228612,0,0,0,0,0,1,0,0,0,0,0,0,114291,114291
457255,228613,0,0,0,0,0,0,0,0,0,1,0,0,114292,114292
457256,228614,0,0,1,0,0,0,0,0,0,0,0,0,114293,114293
457257,228615,0,0,0,0,0,0,0,0,0,0,1,0,114294,114294
457258,228616,0,0,0,1,0,0,0,0,0,0,0,0,114295,114295
457259,228617,0,0,0,0,0,0,0,0,0,0,0,1,114296,114296
457260,228618,0,0,0,0,0,0,1,0,0,0,0,0,114297,114297
457261,228619,0,0,0,0,0,1,0,0,0,0,0,0,114298,114298
457262,228620,0,0,0,0,1,0,0,0,0,0,0,0,114299,114299
457263,228621,0,0,0,0,1,0,0,0,0,0,0,0,114300,114300
457264,228622,0,0,0,0,1,0,0,0,0,0,0,0,114301,114301
457265,228623,0,0,0,0,1,0,0,0,0,0,0,0,114302,114302
457266,228624,0,0,0,0,0,0,1,0,0,0,0,0,114303,114303
457267,228625,0,1,0,0,0,0,0,0,0,0,0,0,114304,114304
457268,228626,1,0,0,0,0,0,0,0,0,0,0,0,114305,114305
457269,228627,0,0,1,0,0,0,0,0,0,0,0,0,114306,114306
457270,228628,0,0,1,0,0,0,0,0,0,0,0,0,114307,114307
457271,228629,0,0,0,1,0,0,0,0,0,0,0,0,114308,114308
457272,228630,0,0,0,1,0,0,0,0,0,0,0,0,114309,114309
457273,228631,0,0,0,0,0,0,0,0,1,0,0,0,114310,114310
457274,228632,0,0,0,0,0,0,0,1,0,0,0,0,114311,114311
457275,228633,0,0,0,0,0,0,0,0,1,0,0,0,114312,114312
457276,228634,0,0,0,0,0,0,0,1,0,0,0,0,114313,114313
457277,228635,1,0,0,0,0,0,0,0,0,0,0,0,114314,114314
457278,228636,0,0,0,0,0,0,0,0,0,0,1,0,114315,114315
457279,228637,0,0,0,0,1,0,0,0,0,0,0,0,114316,114316
457280,228638,0,0,0,0,0,0,0,0,1,0,0,0,114317,114317
457281,228639,0,0,0,1,0,0,0,0,0,0,0,0,114318,114318
457282,228640,0,0,0,0,0,0,0,0,0,1,0,0,114319,114319
457283,228641,0,0,0,0,0,0,1,0,0,0,0,0,114320,114320